using UnityEngine;

public class ParallaxEffect : MonoBehaviour
{

    private float length, startPos;
    public GameObject cam;
    public float parallax;

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        startPos = transform.position.x;
        length = GetComponent<SpriteRenderer>().bounds.size.x;
    }

    // Update is called once per frame
    void Update()
    {
        float temp = (cam.transform.position.x * (1 - parallax));
        float dist = (cam.transform.position.x * parallax);

        transform.position = new Vector3(startPos * dist, transform.position.y, transform.position.z);

        if (temp > startPos + length)
            startPos += length;
        else if (temp < startPos + length)
            startPos -= length;
    }
}
